#!/usr/bin/env bash
# Commit the generated/edited book, push it, and open (or refresh) a PR for the
# issue. EVERY dynamic value arrives via the environment — nothing untrusted is
# interpolated into this script — and all PR/comment bodies go through files, so
# arbitrary issue titles (backticks, quotes, <angle brackets>) can never break
# the shell. Static + `bash -n`-checkable.
#
#   env: ISSUE_NUMBER ISSUE_TITLE REPO SERVER_URL RUN_ID GENERATE_OUTCOME
#        VERIFY_OUTCOME GH_TOKEN
set -euo pipefail
: "${ISSUE_NUMBER:?}" "${REPO:?}" "${GH_TOKEN:?}"

BRANCH="book/issue-${ISSUE_NUMBER}"
RUN_URL="${SERVER_URL:-https://github.com}/${REPO}/actions/runs/${RUN_ID:-}"
OUTCOME="${GENERATE_OUTCOME:-success}"
TITLE="${ISSUE_TITLE:-New book}"
echo "branch=$BRANCH" >> "${GITHUB_OUTPUT:-/dev/null}"

git checkout -B "$BRANCH"
node generator/sync-issue-books.mjs || true        # keep the tweak dropdown current
# apps/bookshelf/src/viz/books: the book's AUTHORED 3b1b scenes (books/<slug>/chapter-<n>.tsx)
# ship with the manifest that references them — dropping them would deploy
# viz steps pointing at scenes that don't exist.
git add -A public/generated apps/bookshelf/src/viz/books .github/ISSUE_TEMPLATE/tweak-book.yml

if git diff --cached --quiet; then
  printf '⚠️ No changes were produced (generation `%s`) — see the [run log](%s).\n' "$OUTCOME" "$RUN_URL" \
    | gh issue comment "$ISSUE_NUMBER" --body-file -
  exit 1
fi

PARTIAL=""
if [ "$OUTCOME" != "success" ]; then
  PARTIAL=1
  echo "partial=true" >> "${GITHUB_OUTPUT:-/dev/null}"
fi

git commit -m "$TITLE (#$ISSUE_NUMBER)"
# checkout's persisted token is gone after the action, so push with an explicitly
# authenticated URL (GITHUB_TOKEN is masked in logs). --force so a re-run resets it.
git push --force "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git" "HEAD:refs/heads/$BRANCH"

# Build the PR body in a file (single-quoted printf → backticks are literal).
body="$(mktemp)"
{
  printf 'Closes #%s\n\n' "$ISSUE_NUMBER"
  printf 'Auto-generated by Claude Code in CI. A **preview** will be posted on this PR shortly.\n'
  printf 'Reply `@claude <change>` to revise; **merge** when you are happy and it deploys to production.\n'
  if [ -n "$PARTIAL" ]; then
    printf '\n> ⚠️ **Generation did not finish (`%s`).** This PR holds the partial work so nothing is lost — reply `@claude <change>` to continue, then merge.\n' "$OUTCOME"
  fi
  # Browser verification (generator/verify-book.mjs): every chapter played in
  # headless Chromium — console clean, viz scenes mounted, previews screenshot.
  case "${VERIFY_OUTCOME:-skipped}" in
    success) printf '\n✅ **Browser-verified** — every chapter played clean in headless Chromium; mid-chapter preview PNGs are committed under `public/generated/<slug>/previews/`.\n' ;;
    failure) printf '\n⚠️ **Browser verification failed** — see the [run log](%s) for the failing chapter/step before merging.\n' "$RUN_URL" ;;
  esac
} > "$body"

PR="$(gh pr list --head "$BRANCH" --state open --json number --jq '.[0].number // empty')"
if [ -z "$PR" ]; then
  gh pr create --base main --head "$BRANCH" --title "$TITLE" --body-file "$body" >/dev/null
  PR="$(gh pr list --head "$BRANCH" --state open --json number --jq '.[0].number // empty')"
  VERB="Opened"
else
  VERB="Refreshed"
fi
PR_URL="${SERVER_URL:-https://github.com}/${REPO}/pull/$PR"
echo "number=$PR" >> "${GITHUB_OUTPUT:-/dev/null}"

note=""
[ -n "$PARTIAL" ] && note=' (generation did not fully finish; the PR holds the partial work)'
printf '📖 %s %s — a Cloudflare **preview link** will appear on it shortly. Reply `@claude <change>` on the PR to revise, and merge when you are happy.%s\n' \
  "$VERB" "$PR_URL" "$note" | gh issue comment "$ISSUE_NUMBER" --body-file -
