// Source: aes_mobius_bridge_cot.pdf, section 2.2 and section 3.
// Persistent object: four projective points transform while their cross-ratio meter remains fixed.
import { CAMERA_HOME, Camera, MathLabel, Timeline, cameraInterp, colors, ease } from '../../core';
import type { CameraState, SceneState } from '../../core';
import { Arrow, Chip, Panel, ResearchTitle, clamp01, mono } from '../../book-components/research';

const BASE = [-0.82, -0.28, 0.36, 0.78];
const sx = (v: number) => 170 + ((v + 1) / 2) * 940;

export function buildScene() {
  const tl = new Timeline();
  const cam = tl.channel<CameraState>('cam', CAMERA_HOME, cameraInterp);
  const lineU = tl.channel('lineU', 0);
  const pointsU = tl.channel('pointsU', 0);
  const translateU = tl.channel('translateU', 0);
  const invertU = tl.channel('invertU', 0);
  const affineU = tl.channel('affineU', 0);
  const meterU = tl.channel('meterU', 0);
  const tripletU = tl.channel('tripletU', 0);
  const roundsU = tl.channel('roundsU', 0);
  const breakU = tl.channel('breakU', 0);
  let t = 0.4;
  t = tl.caption({ at: t, dur: 5.6, text: 'Take four distinct field elements. Their cross-ratio measures the projective shape of the ordered quadruple.' });
  tl.tween(lineU, 1, { at: 0.8, dur: 1.2, ease: ease.draw });
  tl.tween(pointsU, 1, { at: 1.4, dur: 1.2, ease: ease.enter });
  tl.tween(meterU, 1, { at: 2.0, dur: 0.7, ease: ease.pop });
  t = tl.hold(t, 0.5);
  t = tl.caption({ at: t, dur: 5.6, text: 'Add the same key byte to all four. Every difference keeps that translation twice, so it cancels from the ratio.' });
  tl.tween(translateU, 1, { at: t - 5.0, dur: 1.4, ease: ease.move });
  t = tl.hold(t, 0.5);
  t = tl.caption({ at: t, dur: 5.8, text: 'Invert all four elements. Numerators and denominators acquire the same product, which cancels again.' });
  tl.tween(invertU, 1, { at: t - 5.2, dur: 1.5, ease: ease.move });
  tl.tween(cam, { x: 640, y: 330, k: 1.05 }, { at: t - 5.0, dur: 1.2, ease: ease.move });
  t = tl.hold(t, 0.5);
  t = tl.caption({ at: t, dur: 5.8, text: 'Scaling and shifting preserve it too. Together, those operations are the Möbius transformations generated by key addition and the substitution box core.' });
  tl.tween(affineU, 1, { at: t - 5.2, dur: 1.5, ease: ease.move });
  t = tl.hold(t, 0.5);
  t = tl.caption({ at: t, dur: 5.7, text: 'Two or three points cannot carry a nontrivial invariant under this group. Four points are the first place projective shape survives.' });
  tl.tween(tripletU, 1, { at: t - 5.0, dur: 1.0, ease: ease.enter });
  t = tl.hold(t, 0.5);
  t = tl.caption({ at: t, dur: 5.8, text: 'Hand propagation predicts one shared ratio after round one, four ratios after round two, and then full diffusion mixes unrelated quadruples.' });
  tl.tween(roundsU, 1, { at: t - 5.2, dur: 1.8, ease: ease.draw });
  t = tl.hold(t, 0.5);
  t = tl.caption({ at: t, dur: 5.8, text: 'The experiment confirms the boundary exactly. The invariant is real, key-independent through the early layers, and broken precisely when the derivation says it should break.' });
  tl.tween(breakU, 1, { at: t - 5.2, dur: 1.0, ease: ease.pop });
  tl.tween(cam, CAMERA_HOME, { at: t - 2.0, dur: 1.2, ease: ease.move });
  return { tl, cam, lineU, pointsU, translateU, invertU, affineU, meterU, tripletU, roundsU, breakU };
}
const scene = buildScene();

function moved(v: number, trans: number, inv: number, aff: number) {
  const a = v + 0.24 * trans;
  const b = a + ((Math.sign(a || 1) * Math.min(1, 0.22 / Math.max(0.18, Math.abs(a)))) - a) * inv;
  return Math.max(-0.96, Math.min(0.96, b * (1 + 0.28 * aff) - 0.16 * aff));
}

export function Render({ s }: { s: SceneState }) {
  const p = s.get(scene.pointsU);
  const vals = BASE.map((v) => moved(v, s.get(scene.translateU), s.get(scene.invertU), s.get(scene.affineU)));
  return (
    <Camera {...s.get(scene.cam)}>
      <ResearchTitle kicker="Finding the Bridge · 2" title="Four points survive" />
      <Panel x={75} y={145} w={1130} h={260} opacity={s.get(scene.lineU)} accent={colors.SECONDARY}>
        <line x1={150} y1={290} x2={1130} y2={290} stroke={colors.GRID} strokeWidth={2} />
        {vals.map((v, i) => (
          <g key={i} opacity={p} transform={`translate(${sx(v)},290)`}>
            <circle r={16} fill={[colors.ACCENT, colors.SECONDARY, colors.WARM, colors.POSITIVE][i]} />
            <text y={-28} textAnchor="middle" fill={colors.TEXT} fontSize={13} fontFamily={mono}>{['a', 'b', 'c', 'd'][i]}</text>
          </g>
        ))}
        <MathLabel tex={'\\chi(a,b;c,d)=\\frac{(a+c)(b+d)}{(a+d)(b+c)}'} x={640} y={360} opacity={s.get(scene.meterU)} />
      </Panel>
      <g opacity={s.get(scene.meterU)}>
        <Chip x={250} y={470} text="AddRoundKey" color={colors.ACCENT} width={150} />
        <Arrow x1={330} y1={470} x2={440} y2={470} reveal={s.get(scene.translateU)} />
        <Chip x={520} y={470} text="Inv" color={colors.SECONDARY} width={90} />
        <Arrow x1={570} y1={470} x2={680} y2={470} reveal={s.get(scene.invertU)} />
        <Chip x={765} y={470} text="affine" color={colors.WARM} width={100} />
        <Chip x={1010} y={470} text="χ unchanged" opacity={s.get(scene.affineU)} color={colors.POSITIVE} width={150} />
      </g>
      <g opacity={s.get(scene.tripletU)}>
        <text x={150} y={555} fill={colors.NEGATIVE} fontFamily={mono} fontSize={12}>2 or 3 points · no invariant</text>
        <text x={960} y={555} fill={colors.POSITIVE} fontFamily={mono} fontSize={12}>4 points · one cross-ratio</text>
      </g>
      <g opacity={s.get(scene.roundsU)}>
        {['round 1 · one χ', 'round 2 · four χ', 'round 3 · mixed'].map((x, i) => (
          <Chip key={x} x={330 + i * 310} y={595} text={x} color={i === 2 && s.get(scene.breakU) ? colors.NEGATIVE : colors.ACCENT} width={210} />
        ))}
      </g>
    </Camera>
  );
}
export const vizScene = () => scene;
