import type { Story } from '../types';

// How the keychain works in almostnode/apps/web-ide.
// Generated by reading src/features/keychain.ts, credential-mirror.ts, and
// src/features/oauth-services/*. Secrets are stored as files in a per-sandbox
// virtual filesystem, mirrored — encrypted — into a passkey-protected vault in
// localStorage, and restored back into every open sandbox on unlock.
export const keychainStory: Story = {
  title: 'The Keychain',
  subtitle: 'How web-ide keeps your secrets — entirely in the browser',

  nodes: [
    { id: 'sidebar', label: 'Keychain Sidebar', kind: 'client', x: 9, y: 18, sublabel: 'sign in here' },
    { id: 'cli', label: 'CLI Tool', kind: 'worker', x: 27, y: 20, sublabel: 'claude · gh · aws' },
    { id: 'mirror', label: 'Credential Mirror', kind: 'cache', x: 9, y: 49, sublabel: 'unencrypted · live' },
    { id: 'orch', label: 'OAuth Orchestrator', kind: 'loadbalancer', x: 9, y: 81, sublabel: 'GitHub · Fly · Neon' },
    { id: 'provider', label: 'OAuth Provider', kind: 'external', x: 28, y: 83, sublabel: 'identity provider' },
    { id: 'vfs', label: 'Sandbox VFS', kind: 'database', x: 47, y: 40, sublabel: '~/.config on disk' },
    { id: 'vfs2', label: 'Background VFS', kind: 'database', x: 47, y: 70, sublabel: 'another session' },
    { id: 'keychain', label: 'Keychain', kind: 'service', x: 69, y: 50, sublabel: 'watch · encrypt' },
    { id: 'vault', label: 'Encrypted Vault', kind: 'vault', x: 89, y: 26, sublabel: 'localStorage · AES-GCM' },
    { id: 'passkey', label: 'Passkey', kind: 'key', x: 89, y: 68, sublabel: 'WebAuthn PRF' },
  ],

  edges: [
    { id: 'sidebar-cli', from: 'sidebar', to: 'cli' },
    { id: 'cli-vfs', from: 'cli', to: 'vfs' },
    { id: 'keychain-vfs', from: 'keychain', to: 'vfs' },
    { id: 'keychain-passkey', from: 'keychain', to: 'passkey' },
    { id: 'keychain-vault', from: 'keychain', to: 'vault' },
    { id: 'mirror-vfs', from: 'mirror', to: 'vfs' },
    { id: 'keychain-vfs2', from: 'keychain', to: 'vfs2', dashed: true },
    { id: 'mirror-vfs2', from: 'mirror', to: 'vfs2', dashed: true },
    { id: 'orch-provider', from: 'orch', to: 'provider' },
    { id: 'orch-vfs', from: 'orch', to: 'vfs' },
  ],

  steps: [
    {
      id: 'cover',
      cue: 0,
      chapter: 'Chapter 2',
      cover: true,
      title: 'The Keychain',
      coverSubtitle: 'How a browser IDE stores your secrets — with no server in sight.',
      narration: 'A secret’s journey from sign-in to an encrypted, passkey-locked vault and back.',
    },
    {
      id: 'problem',
      cue: "command line tools",
      chapter: 'The setup',
      title: 'Real CLIs, running in your browser',
      narration:
        'web-ide runs real command-line tools — `claude`, `gh`, `aws` — inside a sandbox in the browser tab. They expect to read credentials **from disk**. So each sandbox gets a **virtual filesystem (VFS)** where those credential files can live.',
      reveal: ['vfs', 'cli'],
      highlight: ['vfs', 'cli'],
      messages: [{ from: 'vfs', to: 'cli', kind: 'data', label: 'reads ~/.config' }],
    },
    {
      id: 'signin',
      cue: "normal login command",
      chapter: 'A secret enters',
      title: 'You sign in',
      narration:
        'From the **Keychain sidebar** you click “Sign in”. The sidebar doesn’t write the secret itself — it **runs a CLI command** in the sandbox (like `claude login`). The CLI performs the login and writes a plain-text credential file to disk — i.e. into the **VFS**.',
      reveal: ['sidebar'],
      highlight: ['sidebar', 'cli', 'vfs'],
      messages: [
        { from: 'sidebar', to: 'cli', kind: 'request', label: 'run claude login' },
        { from: 'cli', to: 'vfs', kind: 'data', label: 'write .credentials.json', delay: 950 },
      ],
    },
    {
      id: 'watch',
      cue: "sees that file appear",
      chapter: 'The keychain wakes up',
      title: 'The keychain is watching',
      narration:
        'The **Keychain** arms file-system watchers on the VFS. The moment a managed file changes, it snapshots every credential file.',
      reveal: ['keychain'],
      highlight: ['keychain', 'vfs'],
      messages: [{ from: 'vfs', to: 'keychain', kind: 'event', label: 'file changed' }],
    },
    {
      id: 'slots',
      cue: "registered locations",
      chapter: 'The keychain wakes up',
      title: 'Only registered paths count',
      narration:
        'It doesn’t grab *everything*. Each credential lives in a registered **slot** — `registerSlot(\'claude\', [\'/home/user/.claude/.credentials.json\'])`. A write to any unregistered path is ignored, so stray files never leak into the vault.',
      highlight: ['keychain'],
      badges: [{ node: 'keychain', text: 'scoped', tone: 'info' }],
    },
    {
      id: 'passkey',
      cue: "asks your passkey",
      chapter: 'Locking it down',
      title: 'Your passkey makes the key',
      narration:
        'To encrypt, the Keychain needs a key — but it **never stores one**. It asks your **passkey** via the WebAuthn PRF extension. Touch ID returns a secret that derives an AES-GCM key: `deriveVaultKeyFromPrf(prfOutput, prfSalt)`.',
      reveal: ['passkey'],
      highlight: ['keychain', 'passkey'],
      messages: [
        { from: 'keychain', to: 'passkey', kind: 'request', label: 'WebAuthn PRF' },
        { from: 'passkey', to: 'keychain', kind: 'response', label: 'derive key', delay: 1050 },
      ],
    },
    {
      id: 'encrypt',
      cue: "local storage",
      chapter: 'Locking it down',
      title: 'Encrypted at rest',
      narration:
        'With that key, the snapshot is encrypted and written to **localStorage** as `almostnode.webide.keychain.v2` — only `{ iv, ciphertext, credentialId, prfSalt }`. The key itself lives in memory and disappears when the tab closes.',
      reveal: ['vault'],
      highlight: ['keychain', 'vault'],
      badges: [{ node: 'vault', text: 'encrypted', tone: 'ok' }],
      messages: [{ from: 'keychain', to: 'vault', kind: 'data', label: 'AES-GCM' }],
    },
    {
      id: 'unlock',
      cue: "reopen the environment",
      chapter: 'Coming back',
      title: 'Reopening the IDE',
      narration:
        'Next time you open web-ide the VFS starts **empty**. The Keychain reads the vault, prompts your passkey to `unlockVaultKey()`, decrypts the snapshot, and writes the files back into the VFS with `restoreIntoVfs()`.',
      highlight: ['vault', 'keychain', 'vfs'],
      messages: [
        { from: 'vault', to: 'keychain', kind: 'data', label: 'ciphertext', duration: 800 },
        { from: 'keychain', to: 'vfs', kind: 'data', label: 'restore files', delay: 950 },
      ],
    },
    {
      id: 'cli-reads',
      cue: "simply there",
      chapter: 'Coming back',
      title: 'The tools just work',
      narration:
        'As far as the `claude` CLI knows, `~/.claude/.credentials.json` was simply *there* on disk. It never sees the vault, the passkey, or any encryption — it just opens a file and reads it.',
      highlight: ['vfs', 'cli'],
      messages: [{ from: 'vfs', to: 'cli', kind: 'data', label: 'reads creds' }],
    },
    {
      id: 'mirror',
      cue: "live only mirror",
      chapter: 'Without unlocking',
      title: 'A fast, unencrypted mirror',
      narration:
        'Some routes spin up a sandbox *before* you’ve tapped your passkey. A **Credential Mirror** keeps an unencrypted copy in localStorage and `hydrateFromStorage()` writes it into each new VFS. It’s live-only — cleared when the tab closes.',
      reveal: ['mirror'],
      highlight: ['mirror', 'vfs'],
      badges: [{ node: 'mirror', text: 'live only', tone: 'warn' }],
      messages: [{ from: 'mirror', to: 'vfs', kind: 'data', label: 'hydrate' }],
    },
    {
      id: 'multi',
      cue: "several sandboxes",
      chapter: 'Many sandboxes at once',
      title: 'One keychain, many filesystems',
      narration:
        'You can run several sandboxes at once. The Keychain tracks a **primary VFS** plus **auxiliaries** (`attachAuxiliaryVfs`). On unlock, *every* VFS gets the restored files — and a **newest-wins** merge means the freshest token always wins.',
      reveal: ['vfs2'],
      highlight: ['keychain', 'vfs', 'vfs2'],
      badges: [{ node: 'keychain', text: 'primary + aux', tone: 'info' }],
      messages: [
        { from: 'keychain', to: 'vfs', kind: 'data', label: 'restore', duration: 700 },
        { from: 'keychain', to: 'vfs2', kind: 'data', label: 'restore', delay: 250, duration: 700 },
        { from: 'mirror', to: 'vfs2', kind: 'data', label: 'hydrate', delay: 600 },
      ],
    },
    {
      id: 'oauth',
      cue: "outside services",
      chapter: 'Connecting services',
      title: 'Adding an OAuth service',
      narration:
        'Beyond the built-in tools you can connect services — GitHub, AWS, Fly, Neon, Netlify. The **OAuth Orchestrator** discovers the provider, opens an authorization popup, and exchanges the returned code for tokens.',
      reveal: ['orch', 'provider'],
      highlight: ['orch', 'provider'],
      messages: [
        { from: 'orch', to: 'provider', kind: 'request', label: 'authorize' },
        { from: 'provider', to: 'orch', kind: 'response', label: 'code → tokens', delay: 1050 },
      ],
    },
    {
      id: 'tokens',
      cue: "same journey",
      chapter: 'Connecting services',
      title: 'Tokens take the same path',
      narration:
        'The orchestrator writes the tokens to a file on the VFS. From there it’s the exact same story: the Keychain snapshots the change and encrypts it into the vault.',
      highlight: ['orch', 'vfs', 'keychain', 'vault'],
      messages: [
        { from: 'orch', to: 'vfs', kind: 'data', label: 'token file', duration: 700 },
        { from: 'vfs', to: 'keychain', kind: 'event', label: 'changed', delay: 850, duration: 600 },
        { from: 'keychain', to: 'vault', kind: 'data', label: 'encrypt', delay: 1550, duration: 600 },
      ],
    },
    {
      id: 'refresh',
      cue: "refreshes tokens",
      chapter: 'Connecting services',
      title: 'Kept fresh automatically',
      narration:
        'While unlocked, the orchestrator runs `refreshAll()` every 60 seconds. Tokens near expiry are refreshed with the provider, rewritten to the VFS, and re-encrypted — so long-running sessions never silently expire.',
      highlight: ['orch', 'provider'],
      badges: [{ node: 'orch', text: 'every 60s', tone: 'info' }],
      messages: [
        { from: 'orch', to: 'provider', kind: 'request', label: 'refresh_token' },
        { from: 'provider', to: 'orch', kind: 'response', label: 'new token', delay: 1000 },
      ],
    },
    {
      id: 'recap',
      cue: "that's the keychain",
      chapter: 'The whole picture',
      title: 'That’s the keychain',
      narration:
        'Secrets enter through the **sidebar** or **OAuth**, land as plain files in the **VFS** where tools read them, and the **Keychain** mirrors them — encrypted — into a **passkey-protected vault** in localStorage, across every sandbox you have open. No server ever sees them.',
      autoAdvanceMs: 8500,
      messages: [
        { from: 'sidebar', to: 'cli', kind: 'request', label: 'login', delay: 0, duration: 450 },
        { from: 'cli', to: 'vfs', kind: 'data', label: 'write', delay: 450, duration: 450 },
        { from: 'vfs', to: 'keychain', kind: 'event', label: 'watch', delay: 950, duration: 450 },
        { from: 'keychain', to: 'passkey', kind: 'request', label: 'passkey', delay: 1450, duration: 450 },
        { from: 'keychain', to: 'vault', kind: 'data', label: 'encrypt', delay: 2000, duration: 450 },
        { from: 'keychain', to: 'vfs', kind: 'data', label: 'restore', delay: 2550, duration: 450 },
        { from: 'vfs', to: 'cli', kind: 'data', label: 'read', delay: 3100, duration: 450 },
      ],
    },
  ],
};
