// Grounding: research/failure-taxonomy/05_report.py; canonical_mode_map.v1.json;
// pair_labels_v1.jsonl; labels_raw.jsonl. Counts: 8,135 trials, 240 coded, 238 valid, 12 modes.
import { CAMERA_HOME, Camera, Timeline, cameraInterp, colors, ease } from '../../core'; import type { CameraState,SceneState } from '../../core';
const dots=Array.from({length:180},(_,i)=>({x:95+(i%30)*37,y:130+Math.floor(i/30)*34})); const modes=['guided success','self-directed','verification','tool misuse','logic error','brittle context','ignored guidance','misapplied skill','timeout','runtime','boundary','other'];
export function buildScene(){const tl=new Timeline(); const cam=tl.channel<CameraState>('cam',CAMERA_HOME,cameraInterp), trials=tl.channel('trial field',0), sample=tl.channel('open coded sample',0), valid=tl.channel('valid labels',0), taxonomy=tl.channel('twelve modes',0), contrast=tl.channel('anchor contrast',0), recap=tl.channel('recap path',0), close=tl.channel('closing focus',0);
tl.caption({at:.4,dur:6.4,text:'Aggregate scores hide the mechanism, so the study normalizes eight thousand one hundred thirty-five trial records.'}); tl.tween(trials,1,{at:.8,dur:2,ease:ease.enter});
tl.caption({at:7.4,dur:6.4,text:'Researchers open-code two hundred forty records, pairing raw, workflow, and skill trajectories task by task.'}); tl.tween(sample,1,{at:8,dur:1.5,ease:ease.move}); tl.tween(cam,{x:640,y:300,k:1.18},{at:9,dur:1.2,ease:ease.move});
tl.caption({at:14.4,dur:6.4,text:'Two records fail validation. Two hundred thirty-eight labels remain as evidence, not anecdotes.'}); tl.tween(valid,1,{at:15,dur:1.2,ease:ease.move});
tl.caption({at:21.2,dur:6.4,text:'Those labels consolidate into twelve skill-use modes and three high-level categories.'}); tl.tween(taxonomy,1,{at:21.8,dur:1.8,ease:ease.draw}); tl.tween(cam,CAMERA_HOME,{at:23,dur:1.2,ease:ease.move});
tl.caption({at:28.2,dur:6.5,text:'On one side, a procedure anchors tool order and verification. On the other, context violates its assumptions.'}); tl.tween(contrast,1,{at:28.8,dur:1.4,ease:ease.move});
tl.caption({at:35.2,dur:6.5,text:'Misapplied or ignored guidance creates a new failure boundary that raw execution did not have.'}); tl.tween(contrast,2,{at:35.8,dur:1.2,ease:ease.move});
tl.caption({at:42.2,dur:6.7,text:'Now retrace the evidence: trajectory, procedure card, retrieval test, then paired audit.'}); tl.tween(recap,1,{at:42.8,dur:3.2,ease:ease.linear});
tl.caption({at:49.4,dur:7,text:'Skills stabilize execution when their procedure fits. They fail when brittle assumptions meet a different world.'}); tl.tween(close,1,{at:50,dur:1.2,ease:ease.move}); tl.hold(56.8,1); return{tl,cam,trials,sample,valid,taxonomy,contrast,recap,close}}
const scene=buildScene();
export function Render({s}:{s:SceneState}){const c=s.get(scene.close),tr=s.get(scene.trials),sa=s.get(scene.sample),va=s.get(scene.valid),tx=s.get(scene.taxonomy),co=s.get(scene.contrast); return <Camera {...s.get(scene.cam)}><text x="640" y="72" textAnchor="middle" fill={colors.TEXT} fontSize="34" fontWeight="700">Audit the anchor</text>
<g opacity={(1-c)*Math.max(0,1-co*4)}>{dots.map((d,i)=><circle key={i} cx={d.x} cy={d.y} r="6" fill={i<Math.floor(180*tr)?(i<24?colors.ACCENT:'#334155'):'#111827'} opacity={i<24?1:.55}/>)}<text x="640" y="365" textAnchor="middle" fill={colors.TEXT} fontSize="34" opacity={tr}>8,135 trials</text></g>
<g opacity={sa*(1-c)*Math.max(0,1-co*4)}><rect x="335" y="390" width="610" height="76" rx="20" fill="#111827" stroke={colors.ACCENT}/><text x="640" y="438" textAnchor="middle" fill={colors.TEXT} fontSize="28">240 open-coded records</text></g>
<g opacity={va*(1-c)*Math.max(0,1-co*4)}><text x="640" y="505" textAnchor="middle" fill={colors.POSITIVE} fontSize="26">238 valid labels</text><text x="875" y="505" fill={colors.NEGATIVE} fontSize="18">2 rejected</text></g>
<g opacity={tx*(1-c)*Math.max(0,1-co*4)}>{modes.map((m,i)=>{const a=(Math.PI*2*i/12)-Math.PI/2,x=640+250*Math.cos(a),y=335+190*Math.sin(a);return <g key={m}><line x1="640" y1="335" x2={x} y2={y} stroke={i<4?colors.POSITIVE:i<8?colors.WARM:colors.NEGATIVE} opacity=".35"/><circle cx={x} cy={y} r="24" fill="#111827" stroke={i<4?colors.POSITIVE:i<8?colors.WARM:colors.NEGATIVE}/><text x={x} y={y+42} textAnchor="middle" fill={colors.MUTED} fontSize="13">{m}</text></g>})}<text x="640" y="328" textAnchor="middle" fill={colors.TEXT} fontSize="25">12 modes</text><text x="640" y="358" textAnchor="middle" fill={colors.MUTED} fontSize="17">3 categories</text></g>
<g opacity={Math.max(0,Math.min(1,(co-.15)*2))*(1-c)}><rect x="155" y="190" width="400" height="250" rx="28" fill="#111827" stroke={colors.POSITIVE} strokeWidth="3"/><text x="355" y="245" textAnchor="middle" fill={colors.POSITIVE} fontSize="28">procedural anchor</text>{['ordered steps','tool choice','verification'].map((x,i)=><text key={x} x="355" y={300+i*38} textAnchor="middle" fill={colors.TEXT} fontSize="21">✓ {x}</text>)}<rect x="725" y="190" width="400" height="250" rx="28" fill="#111827" stroke={colors.NEGATIVE} strokeWidth="3"/><text x="925" y="245" textAnchor="middle" fill={colors.NEGATIVE} fontSize="28">brittle context</text>{['assumption breaks','guidance ignored','skill misapplied'].map((x,i)=><text key={x} x="925" y={300+i*38} textAnchor="middle" fill={colors.TEXT} fontSize="21">× {x}</text>)}</g>
<g opacity={Math.max(0,co-1)*(1-c)}><path d="M 555 315 C 630 250 650 410 725 315" fill="none" stroke={colors.NEGATIVE} strokeWidth="8" strokeDasharray="14 10"/><text x="640" y="475" textAnchor="middle" fill={colors.NEGATIVE} fontSize="25">new failure boundary</text></g>
<g opacity={s.get(scene.recap)*(1-c)}><path d="M 170 560 H 1110" stroke={colors.ACCENT} strokeWidth="6"/><circle cx={170+940*s.get(scene.recap)} cy="560" r="14" fill={colors.WARM}/>{['trajectory','card','retrieve','audit'].map((x,i)=><text key={x} x={170+i*313} y="600" textAnchor="middle" fill={colors.TEXT} fontSize="18">{x}</text>)}</g>
<g opacity={c}><rect x="220" y="175" width="840" height="320" rx="32" fill="#0a0e1a" stroke={colors.ACCENT} strokeWidth="3"/><text x="640" y="285" textAnchor="middle" fill={colors.TEXT} fontSize="42" fontWeight="700">the procedure must fit the world</text><text x="640" y="365" textAnchor="middle" fill={colors.POSITIVE} fontSize="25">fit → execution stabilizes</text><text x="640" y="412" textAnchor="middle" fill={colors.NEGATIVE} fontSize="25">brittle assumption → failure boundary</text></g></Camera>}
export const vizScene=()=>scene;
