// Grounding: pm2s-clean/README.md; pm2s-clean/scripts/retrieval/run_agent_pick.py;
// README.md retrieval results. The three retrieval arms are independent diagnostics.
import { CAMERA_HOME, Camera, Timeline, cameraInterp, colors, ease } from '../../core'; import type { CameraState,SceneState } from '../../core';
const rows=[{name:'embedding top-one',a:88.3,b:76.9,color:colors.ACCENT},{name:'actual use',a:29.6,b:3.3,color:colors.NEGATIVE},{name:'task success',a:39,b:36,color:colors.POSITIVE}];
export function buildScene(){const tl=new Timeline(); const cam=tl.channel<CameraState>('cam',CAMERA_HOME,cameraInterp), axes=tl.channel('diagnostic rails',0), pool=tl.channel('pool size',0), embed=tl.channel('embedding trace',0), use=tl.channel('actual use trace',0), success=tl.channel('success trace',0), split=tl.channel('independent arms',0), close=tl.channel('closing focus',0);
tl.caption({at:.4,dur:6.3,text:'Finding a relevant skill sounds like one step, but the study measures three different questions.'}); tl.tween(axes,1,{at:.8,dur:1.4,ease:ease.draw});
tl.caption({at:7.3,dur:6.3,text:'Turn the candidate pool from five skills to one hundred, and the search problem gets crowded.'}); tl.tween(pool,1,{at:7.8,dur:5,ease:ease.linear});
tl.caption({at:14.2,dur:6.4,text:'Embedding top-one precision slips from eighty-eight point three to seventy-six point nine percent.'}); tl.tween(embed,1,{at:14.8,dur:1.5,ease:ease.draw}); tl.tween(cam,{x:620,y:235,k:1.08},{at:15.5,dur:1.2,ease:ease.move});
tl.caption({at:21.1,dur:6.5,text:'Parsed actual-use precision falls much harder, from twenty-nine point six to three point three percent.'}); tl.tween(use,1,{at:21.7,dur:1.5,ease:ease.draw}); tl.tween(cam,{x:620,y:370,k:1.08},{at:22.5,dur:1.2,ease:ease.move});
tl.caption({at:28.2,dur:6.4,text:'Yet downstream success stays in a narrow band around thirty-six to thirty-nine percent.'}); tl.tween(success,1,{at:28.8,dur:1.5,ease:ease.draw}); tl.tween(cam,{x:620,y:510,k:1.08},{at:29.5,dur:1.2,ease:ease.move});
tl.caption({at:35.2,dur:6.6,text:'Offline ranking, explicit agent selection, and real execution are independent diagnostic arms.'}); tl.tween(split,1,{at:35.8,dur:1.2,ease:ease.enter}); tl.tween(cam,CAMERA_HOME,{at:37,dur:1.3,ease:ease.move});
tl.caption({at:42.3,dur:6.5,text:'The output of one arm is not passed into the next. Similar curves do not make a serial pipeline.'}); tl.tween(split,2,{at:42.9,dur:1.2,ease:ease.move});
tl.caption({at:49.2,dur:6.7,text:'Exact ground-truth invocation is neither sufficient nor necessary for completing the task.'}); tl.tween(close,1,{at:49.8,dur:1.2,ease:ease.move}); tl.hold(56.2,1); return{tl,cam,axes,pool,embed,use,success,split,close}}
const scene=buildScene();
export function Render({s}:{s:SceneState}){const c=s.get(scene.close), ps=s.get(scene.pool), us=[s.get(scene.embed),s.get(scene.use),s.get(scene.success)]; const x=(u:number)=>230+820*u, y=(r:number,v:number)=>[245,385,525][r]-v*1.25; return <Camera {...s.get(scene.cam)}><text x="640" y="72" textAnchor="middle" fill={colors.TEXT} fontSize="34" fontWeight="700">Retrieval is not use</text>
<g opacity={s.get(scene.axes)*(1-c)}>{rows.map((r,i)=><g key={r.name}><line x1="230" x2="1050" y1={y(i,0)} y2={y(i,0)} stroke="#334155"/><text x="205" y={y(i,0)+5} textAnchor="end" fill={r.color} fontSize="18">{r.name}</text><text x="230" y={y(i,0)+28} fill={colors.MUTED} fontSize="14">5</text><text x="1030" y={y(i,0)+28} fill={colors.MUTED} fontSize="14">100 skills</text></g>)}</g>
{rows.map((r,i)=>{const u=us[i]; const x2=x(u), y1=y(i,r.a), y2=y(i,r.a+(r.b-r.a)*u); return <g key={r.name} opacity={(u>0?1:0)*(1-c)}><line x1={x(0)} y1={y1} x2={x2} y2={y2} stroke={r.color} strokeWidth="7" strokeLinecap="round"/><circle cx={x2} cy={y2} r="9" fill={r.color}/><text x={x(0)} y={y1-14} fill={r.color} fontSize="17">{r.a}%</text><text x={x2} y={y2-14} textAnchor="end" fill={r.color} fontSize="17">{(r.a+(r.b-r.a)*u).toFixed(1)}%</text></g>})}
<g opacity={Math.min(1,s.get(scene.split))*(1-c)}>{['embedding rank','agent pick','real execution'].map((t,i)=><g key={t}><rect x={245+i*300} y="120" width="230" height="55" rx="16" fill="#111827" stroke={[colors.ACCENT,colors.SECONDARY,colors.POSITIVE][i]}/><text x={360+i*300} y="154" textAnchor="middle" fill={colors.TEXT} fontSize="18">{t}</text></g>)}</g>
<circle cx={230+820*ps} cy="610" r="10" fill={colors.WARM} opacity={(1-c)}/><line x1="230" x2="1050" y1="610" y2="610" stroke={colors.MUTED} opacity={1-c}/>
<g opacity={c}><rect x="230" y="185" width="820" height="300" rx="30" fill="#0a0e1a" stroke={colors.WARM} strokeWidth="3"/><text x="640" y="290" textAnchor="middle" fill={colors.TEXT} fontSize="38" fontWeight="700">retrieved ≠ used ≠ solved</text><text x="640" y="365" textAnchor="middle" fill={colors.MUTED} fontSize="25">measure each claim on its own rail</text></g></Camera>}
export const vizScene=()=>scene;
