import {test} from 'node:test';import assert from 'node:assert/strict';import {build} from 'esbuild';
const r=await build({stdin:{contents:"export * from './apps/bookshelf/src/viz/three/primitives/index'; export * from './apps/bookshelf/src/viz/three/examples/data'; export * from './apps/bookshelf/src/viz/three/examples/compositions';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false,external:['three']});
const code=r.outputFiles[0].text.replaceAll('"three"',JSON.stringify(import.meta.resolve('three')));const p=await import('data:text/javascript;base64,'+Buffer.from(code).toString('base64'));
test('convolution uses the full patch and produces the expected valid shape',()=>{assert.deepEqual(p.convolveValid([1,2,3,4,5,6,7,8,9],3,3,[1,0,0,-1],2),{values:[-4,-4,-4,-4],width:2,height:2});assert.equal(p.MAPS[0].values.length,36);});
test('softmax remains normalized for large logits',()=>{const values=p.softmax([1000,1001,999]);assert.ok(Math.abs(values.reduce((a,b)=>a+b)-1)<1e-12);assert.ok(values[1]>values[0]&&values[0]>values[2]);});
test('tensor keeps true shape while limiting rendered cell count',()=>{const t=p.tensorVolume({shape:[55,55,96],samples:[4,8,8],value:()=>.5});assert.deepEqual(t.root.userData.shape,[55,55,96]);assert.equal(t.root.children[0].count,256);p.disposeThree(t.root);assert.throws(()=>p.featureMap([1],2,2));});
test('explicit dense example has matching shapes and a normalized output',()=>{assert.equal(p.DENSE_HIDDEN.length,6);assert.equal(p.DENSE_PROBS.length,3);assert.ok(Math.abs(p.DENSE_PROBS.reduce((a,b)=>a+b)-1)<1e-12);assert.throws(()=>p.matvec([[1,2]],[1]));});
test('probability bars reject invalid distributions',()=>{assert.throws(()=>p.probabilityBars([.4,.4]));assert.throws(()=>p.probabilityBars([NaN,1]));});
test('compositions reset object transforms and visibility on reverse seeks',()=>{for(const factory of [p.alexNet,p.convolution,p.neuralNetwork,p.mathGallery]){const c=factory();const snapshot=()=>{const items=[];c.root.traverse(o=>items.push([o.name,o.visible,o.position.toArray(),o.scale.toArray()]));return items;};c.sample(7);const first=snapshot();c.sample(c.duration-1);c.sample(7);assert.deepEqual(snapshot(),first);p.disposeThree(c.root);}});
