// Agentic World Models — Chapter 2: the masking trick
//
// Grounding: Cameron R. Wolfe, "Agentic World Models" (Substack, July 2026),
// synthesizing ECHO, "True Agents Model the World", PaW, and Qwen-AgentWorld.
// Chapter 1 established the sparse-reward problem: a long agent trajectory
// gets one reward pulse at the end instead of dense per-step supervision.
// This chapter is the mechanism that fixes it: an agent trajectory is a
// single stream of tokens, some GENERATED by the agent (actions — its own
// words, tool calls) and some fed back in as OBSERVATIONS (tool output,
// terminal responses) that the model never generated. The essay's core move
// is a token-level mask: action tokens get GRPO's advantage-weighted
// policy-gradient loss (advantage from a group of rollouts, no separate
// value function — cheaper than PPO); observation tokens get an ordinary
// supervised next-token loss, which is mathematically RL with a constant
// positive advantage. One mask, one unified loss, negligible extra compute
// over plain RL — no new architecture, no separate value/world model network.
//
// Centerpiece: ONE token stream that transforms across the whole chapter —
// a row of colored chips splits into two rivers (spiky advantage-weighted
// pulses for actions, a steady uniform pulse for observations) that converge
// into a single loss basin. Camera pushes into the mask boundary, then
// pulls back to watch the convergence.
import {
  CAMERA_HOME,
  Camera,
  MathLabel,
  STAGE_H,
  STAGE_W,
  Timeline,
  cameraInterp,
  colors,
  ease,
} from '../../core';
import type { CameraState, SceneState } from '../../core';

const clamp01 = (u: number): number => (u < 0 ? 0 : u > 1 ? 1 : u);
const win = (p: number, n: number, i: number, span: number): number =>
  clamp01((p * (n + span) - i) / span);
const MONO = 'ui-monospace, SFMono-Regular, Menlo, monospace';
const frac = (x: number): number => x - Math.floor(x);

// ---------------------------------------------------------------------------
// Layout — one token stream, split into two rivers, converging on one basin.
// ---------------------------------------------------------------------------

type Kind = 'action' | 'obs';
const KINDS: Kind[] = [
  'action', 'action', 'action', 'obs', 'obs', 'obs',
  'action', 'action', 'obs', 'obs', 'obs',
  'action', 'action', 'action', 'obs', 'obs',
];
const N = KINDS.length;
const TOKEN_Y = 148;
const TOKEN_X0 = 108;
const TOKEN_DX = 68;
const tokenX = (i: number): number => TOKEN_X0 + i * TOKEN_DX;
const kindColor = (k: Kind): string => (k === 'action' ? colors.ACCENT : colors.SECONDARY);

// mask boundary the camera pushes into: between token 2 (action) and 3 (obs)
const MASK_I = 2;
const MASK_X = (tokenX(MASK_I) + tokenX(MASK_I + 1)) / 2;

// merge points where each group's chips visually gather before the rivers
const MERGE_A = { x: 420, y: 262 };
const MERGE_O = { x: 900, y: 262 };
const BASIN = { x: 640, y: 552 };

// deterministic "spiky" advantage weights for the 8 action tokens (group
// baseline makes some actions earn more credit than others)
const ADV_WEIGHTS = [1.6, 0.4, 2.1, 0.9, 1.3, 0.3, 1.8, 1.0];

function bezier(
  x0: number, y0: number, x1: number, y1: number, t: number,
): { x: number; y: number } {
  const cy = (y0 + y1) / 2;
  const u = 1 - t;
  return {
    x: u * u * u * x0 + 3 * u * u * t * x0 + 3 * u * t * t * x1 + t * t * t * x1,
    y: u * u * u * y0 + 3 * u * u * t * cy + 3 * u * t * t * cy + t * t * t * y1,
  };
}
function riverD(x0: number, y0: number, x1: number, y1: number, reveal: number): string {
  const n = 28;
  const upto = Math.max(1, Math.round(n * clamp01(reveal)));
  const parts: string[] = [];
  for (let i = 0; i <= upto; i++) {
    const p = bezier(x0, y0, x1, y1, i / n);
    parts.push(`${i === 0 ? 'M' : 'L'}${p.x.toFixed(1)} ${p.y.toFixed(1)}`);
  }
  return parts.join('');
}

const CAM_MASK: CameraState = { x: MASK_X, y: TOKEN_Y + 10, k: 2.4 };
const CAM_RIVERS: CameraState = { x: 660, y: 340, k: 1.15 };
const CAM_BASIN: CameraState = { x: 640, y: 470, k: 1.3 };

// ---------------------------------------------------------------------------
// Timeline (~92s, twelve beats)
// ---------------------------------------------------------------------------

export function buildScene() {
  const tl = new Timeline();
  const cam = tl.channel<CameraState>('cam', CAMERA_HOME, cameraInterp);

  const streamU = tl.channel('streamU', 0); // token chips reveal, left to right
  const chipActionU = tl.channel('chipActionU', 0); // "action" label chip
  const chipObsU = tl.channel('chipObsU', 0); // "observation" label chip
  const unifyLblU = tl.channel('unifyLblU', 0); // "one loss" caption label
  const gatherU = tl.channel('gatherU', 0); // chips drop into two merge clusters
  const riverAU = tl.channel('riverAU', 0); // action river draw-on
  const riverOU = tl.channel('riverOU', 0); // observation river draw-on
  const grpoChipU = tl.channel('grpoChipU', 0); // "G R P O" chip on action river
  const advChipU = tl.channel('advChipU', 0); // "advantage-weighted" chip
  const supChipU = tl.channel('supChipU', 0); // "constant positive advantage" chip
  const pulseT = tl.channel('pulseT', 0); // linear clock, both rivers' traveling pulses
  const formulaU = tl.channel('formulaU', 0); // KaTeX loss formula
  const maskEqU = tl.channel('maskEqU', 0); // mask-multiplexer emphasis pulse
  const basinU = tl.channel('basinU', 0); // basin appears + glows
  const convergeLblU = tl.channel('convergeLblU', 0); // "one loss" under basin
  const cheapChipU = tl.channel('cheapChipU', 0); // "no new network" closing chip
  const endU = tl.channel('endU', 0); // closing fade + panel

  // — beat 1 · the stream is two kinds of tokens —
  tl.caption({
    at: 0.5,
    dur: 5.6,
    text: 'Zoom into any agent trajectory and you find two very different kinds of tokens tangled together in one stream.',
  });
  tl.tween(streamU, 1, { at: 0.7, dur: 3.2, ease: ease.draw });
  tl.hold(6.3, 0.6);

  // — beat 2 · action vs observation, camera pushes into the boundary —
  tl.caption({
    at: 6.9,
    dur: 6.8,
    text: 'Some tokens were generated by the agent itself, its own words and tool calls. Others are just observations it read back in from the environment.',
  });
  tl.tween(cam, CAM_MASK, { at: 7.1, dur: 1.5, ease: ease.move });
  tl.tween(chipActionU, 1, { at: 8.8, dur: 0.6, ease: ease.enter });
  tl.tween(chipObsU, 1, { at: 9.6, dur: 0.6, ease: ease.enter });
  tl.hold(13.9, 0.6);

  // — beat 3 · training treats them the same, that's the trick —
  tl.caption({
    at: 14.5,
    dur: 5.4,
    text: 'Training treats these two kinds of tokens the same way, and that turns out to be the whole trick.',
  });
  tl.tween(cam, CAMERA_HOME, { at: 14.7, dur: 1.5, ease: ease.move });
  tl.hold(20.1, 0.5);

  // — beat 4 · SFT ≡ RL with constant positive advantage —
  tl.caption({
    at: 20.7,
    dur: 7.6,
    text: 'Supervised fine tuning, ordinary next token prediction, is mathematically the same thing as reinforcement learning with one flat, constant, positive advantage.',
  });
  tl.tween(chipActionU, 0, { at: 21.0, dur: 0.5, ease: ease.enter });
  tl.tween(chipObsU, 0, { at: 21.0, dur: 0.5, ease: ease.enter });
  tl.tween(unifyLblU, 1, { at: 22.4, dur: 0.8, ease: ease.enter });
  tl.hold(28.6, 0.5);

  // — beat 5 · one loss, split by a mask —
  tl.caption({
    at: 29.2,
    dur: 5.8,
    text: 'So instead of two separate training styles, there is really just one loss, split by a mask that knows which token is which.',
  });
  tl.tween(unifyLblU, 0, { at: 29.4, dur: 0.6, ease: ease.enter });
  tl.tween(cam, CAM_RIVERS, { at: 29.6, dur: 1.6, ease: ease.move });
  tl.tween(gatherU, 1, { at: 30.4, dur: 1.6, ease: ease.move });
  tl.tween(riverAU, 1, { at: 32.2, dur: 1.8, ease: ease.draw });
  tl.tween(riverOU, 1, { at: 32.2, dur: 1.8, ease: ease.draw });
  tl.hold(35.4, 0.5);

  // — beat 6 · action tokens: GRPO —
  tl.caption({
    at: 36.0,
    dur: 8.0,
    text: "Action tokens get the reinforcement learning treatment: a policy gradient loss weighted by an advantage computed from a group of rollouts, spoken for short as G R P O.",
  });
  tl.tween(grpoChipU, 1, { at: 36.6, dur: 0.6, ease: ease.enter });
  tl.tween(advChipU, 1, { at: 38.4, dur: 0.6, ease: ease.enter });
  tl.tween(pulseT, 1, { at: 32.2, dur: 60, ease: ease.linear }); // shared traveling-pulse clock
  tl.hold(44.4, 0.5);

  // — beat 7 · spiky advantage —
  tl.caption({
    at: 45.0,
    dur: 7.4,
    text: "That advantage is uneven on purpose. Some actions earned more credit than others against the group's own baseline, so the pulses on this path are spiky.",
  });
  tl.hold(52.8, 0.4);

  // — beat 8 · observation tokens: steady supervised pulse —
  tl.caption({
    at: 53.4,
    dur: 7.6,
    text: 'Observation tokens get the plain supervised treatment instead: the model is simply taught to predict what the environment said, with a constant positive advantage, no spikes at all.',
  });
  tl.tween(advChipU, 0, { at: 53.6, dur: 0.5, ease: ease.enter });
  tl.tween(supChipU, 1, { at: 54.4, dur: 0.6, ease: ease.enter });
  tl.hold(61.4, 0.4);

  // — beat 9 · the formula: a per-token multiplexer —
  tl.caption({
    at: 62.0,
    dur: 7.6,
    text: 'Per token, the loss is just a multiplexer: the action mask times the group relative policy loss, plus the observation mask times that constant supervised weight.',
  });
  tl.tween(cam, CAM_BASIN, { at: 62.2, dur: 1.6, ease: ease.move });
  tl.tween(grpoChipU, 0, { at: 62.4, dur: 0.5, ease: ease.enter });
  tl.tween(supChipU, 0, { at: 62.4, dur: 0.5, ease: ease.enter });
  tl.tween(formulaU, 1, { at: 63.2, dur: 1.0, ease: ease.enter });
  tl.tween(maskEqU, 1, { at: 64.8, dur: 1.6, ease: ease.pop });
  tl.hold(69.9, 0.4);

  // — beat 10 · the two rivers converge —
  tl.caption({
    at: 70.3,
    dur: 6.6,
    text: 'Watch both paths converge into one number. Two training philosophies, folded into a single loss that trains the whole trajectory at once.',
  });
  tl.tween(basinU, 1, { at: 70.6, dur: 1.6, ease: ease.pop });
  tl.tween(convergeLblU, 1, { at: 72.4, dur: 0.8, ease: ease.enter });
  tl.hold(77.2, 0.4);

  // — beat 11 · negligible extra compute —
  tl.caption({
    at: 77.6,
    dur: 7.6,
    text: "And there is no new model to build. Just a mask and a bit of selective bookkeeping over log probabilities, barely more compute than plain reinforcement learning.",
  });
  tl.tween(cheapChipU, 1, { at: 78.4, dur: 0.6, ease: ease.enter });
  tl.hold(85.5, 0.4);

  // — beat 12 · closing: name the trick —
  tl.caption({
    at: 86.0,
    dur: 6.8,
    text: "That's the masking trick: dense supervision on every observation, sparse reward on every action, unified into a single pass of training.",
  });
  tl.tween(cam, CAMERA_HOME, { at: 86.2, dur: 1.6, ease: ease.move });
  tl.tween(endU, 1, { at: 87.4, dur: 1.4, ease: ease.move });
  tl.hold(93.2, 1.4);

  return {
    tl,
    cam,
    streamU,
    chipActionU,
    chipObsU,
    unifyLblU,
    gatherU,
    riverAU,
    riverOU,
    grpoChipU,
    advChipU,
    supChipU,
    pulseT,
    formulaU,
    maskEqU,
    basinU,
    convergeLblU,
    cheapChipU,
    endU,
  };
}

const scene = buildScene();

// ---------------------------------------------------------------------------
// Render
// ---------------------------------------------------------------------------

function Chip({
  x, y, text, color, u, anchor = 'middle',
}: {
  x: number; y: number; text: string; color: string; u: number; anchor?: 'middle' | 'start';
}) {
  if (u <= 0.01) return null;
  const w = text.length * 7.2 + 24;
  const x0 = anchor === 'middle' ? x - w / 2 : x;
  return (
    <g opacity={u}>
      <rect x={x0} y={y - 15} width={w} height={28} rx={8} fill={colors.BG} stroke={color} strokeOpacity={0.75} />
      <text x={x0 + w / 2} y={y + 5} textAnchor="middle" fill={color} fontSize={12.5} fontFamily={MONO}>
        {text}
      </text>
    </g>
  );
}

export function Render({ s }: { s: SceneState }) {
  const cam = s.get(scene.cam);
  const streamU = s.get(scene.streamU);
  const chipActionU = s.get(scene.chipActionU);
  const chipObsU = s.get(scene.chipObsU);
  const unifyLblU = s.get(scene.unifyLblU);
  const gatherU = s.get(scene.gatherU);
  const riverAU = s.get(scene.riverAU);
  const riverOU = s.get(scene.riverOU);
  const grpoChipU = s.get(scene.grpoChipU);
  const advChipU = s.get(scene.advChipU);
  const supChipU = s.get(scene.supChipU);
  const pulseT = s.get(scene.pulseT);
  const formulaU = s.get(scene.formulaU);
  const maskEqU = s.get(scene.maskEqU);
  const basinU = s.get(scene.basinU);
  const convergeLblU = s.get(scene.convergeLblU);
  const cheapChipU = s.get(scene.cheapChipU);
  const endU = s.get(scene.endU);

  const fade = 1 - 0.9 * endU;

  // token chip position: resting in the row, or lerped toward its group's
  // merge point as gatherU rises (the SAME chips, morphed, not re-created)
  const chipPos = (i: number): { x: number; y: number } => {
    const kind = KINDS[i];
    const merge = kind === 'action' ? MERGE_A : MERGE_O;
    const x0 = tokenX(i);
    const y0 = TOKEN_Y;
    return { x: x0 + (merge.x - x0) * gatherU, y: y0 + (merge.y - y0) * gatherU };
  };

  const actionIdx: number[] = [];
  const obsIdx: number[] = [];
  KINDS.forEach((k, i) => (k === 'action' ? actionIdx : obsIdx).push(i));

  return (
    <>
      <rect width={STAGE_W} height={STAGE_H} fill={colors.BG} />
      <Camera {...cam}>
        {/* ---------------- token stream row / gather ---------------- */}
        <g opacity={fade}>
          {KINDS.map((k, i) => {
            const u = win(streamU, N, i, 1.4);
            if (u <= 0) return null;
            const p = chipPos(i);
            const color = kindColor(k);
            return (
              <g key={i} opacity={u}>
                <rect
                  x={p.x - 20}
                  y={p.y - 13}
                  width={40}
                  height={26}
                  rx={6}
                  fill={colors.PANEL}
                  stroke={color}
                  strokeWidth={1.6}
                  strokeOpacity={0.8}
                />
                <circle cx={p.x} cy={p.y} r={3} fill={color} opacity={0.9} />
              </g>
            );
          })}
        </g>

        {/* mask boundary marker (only meaningful before the gather) */}
        <g opacity={fade * (1 - gatherU)}>
          <line
            x1={(tokenX(MASK_I) + tokenX(MASK_I + 1)) / 2}
            y1={TOKEN_Y - 34}
            x2={(tokenX(MASK_I) + tokenX(MASK_I + 1)) / 2}
            y2={TOKEN_Y + 34}
            stroke={colors.WARM}
            strokeWidth={1.4}
            strokeDasharray="4 4"
            opacity={0.5 * (chipActionU + chipObsU) / 2}
          />
          <Chip x={tokenX(MASK_I) - 24} y={TOKEN_Y - 52} text="action" color={colors.ACCENT} u={chipActionU} />
          <Chip x={tokenX(MASK_I + 1) + 24} y={TOKEN_Y - 52} text="observation" color={colors.SECONDARY} u={chipObsU} />
        </g>

        {/* "one loss" unifying label */}
        {unifyLblU > 0.01 && (
          <text
            x={STAGE_W / 2}
            y={TOKEN_Y - 62}
            textAnchor="middle"
            fill={colors.WARM}
            fontSize={16}
            fontStyle="italic"
            opacity={unifyLblU * fade}
          >
            one loss, one mask
          </text>
        )}

        {/* ---------------- the two rivers ---------------- */}
        <g opacity={fade}>
          {riverAU > 0.01 && (
            <path
              d={riverD(MERGE_A.x, MERGE_A.y, BASIN.x, BASIN.y, riverAU)}
              fill="none"
              stroke={colors.ACCENT}
              strokeWidth={12}
              strokeOpacity={0.22}
              strokeLinecap="round"
            />
          )}
          {riverOU > 0.01 && (
            <path
              d={riverD(MERGE_O.x, MERGE_O.y, BASIN.x, BASIN.y, riverOU)}
              fill="none"
              stroke={colors.SECONDARY}
              strokeWidth={12}
              strokeOpacity={0.22}
              strokeLinecap="round"
            />
          )}

          {/* spiky advantage-weighted pulses along the action river */}
          {riverAU > 0.4 &&
            actionIdx.map((tokIdx, k) => {
              const w = ADV_WEIGHTS[k % ADV_WEIGHTS.length];
              const speed = 0.5 + 0.12 * (k % 3);
              const u = frac(pulseT * speed + k * 0.13);
              if (u > riverAU) return null;
              const p = bezier(MERGE_A.x, MERGE_A.y, BASIN.x, BASIN.y, u);
              return (
                <circle key={tokIdx} cx={p.x} cy={p.y} r={3 + 4 * w} fill={colors.ACCENT} opacity={0.55 + 0.25 * w} />
              );
            })}

          {/* steady uniform pulses along the observation river */}
          {riverOU > 0.4 &&
            obsIdx.map((tokIdx, k) => {
              const u = frac(pulseT * 0.5 + k * (1 / obsIdx.length));
              if (u > riverOU) return null;
              const p = bezier(MERGE_O.x, MERGE_O.y, BASIN.x, BASIN.y, u);
              return <circle key={tokIdx} cx={p.x} cy={p.y} r={4.5} fill={colors.SECONDARY} opacity={0.75} />;
            })}

          <Chip x={MERGE_A.x - 30} y={MERGE_A.y - 30} text="G R P O loss" color={colors.ACCENT} u={grpoChipU} />
          <Chip x={MERGE_A.x - 30} y={MERGE_A.y - 62} text="advantage-weighted" color={colors.ACCENT} u={advChipU} />
          <Chip x={MERGE_O.x + 30} y={MERGE_O.y - 30} text="supervised loss" color={colors.SECONDARY} u={supChipU} />
          <Chip x={MERGE_O.x + 30} y={MERGE_O.y - 62} text="constant positive advantage" color={colors.SECONDARY} u={supChipU} />
        </g>

        {/* ---------------- the loss basin ---------------- */}
        {basinU > 0.01 && (
          <g opacity={basinU * fade}>
            <circle cx={BASIN.x} cy={BASIN.y} r={16 + 26 * basinU} fill={colors.WARM} opacity={0.14} />
            <circle cx={BASIN.x} cy={BASIN.y} r={14} fill={colors.PANEL} stroke={colors.WARM} strokeWidth={2} />
          </g>
        )}
        {convergeLblU > 0.01 && (
          <text
            x={BASIN.x}
            y={BASIN.y + 44}
            textAnchor="middle"
            fill={colors.WARM}
            fontSize={14}
            fontWeight={600}
            opacity={convergeLblU * fade}
          >
            one loss
          </text>
        )}

        {/* ---------------- the formula ---------------- */}
        {formulaU > 0.01 && (
          <g opacity={formulaU * fade}>
            <rect
              x={STAGE_W / 2 - 340}
              y={330}
              width={680}
              height={92}
              rx={14}
              fill={colors.PANEL}
              stroke={colors.WARM}
              strokeOpacity={0.3 + 0.5 * maskEqU}
            />
            <MathLabel
              tex={'\\mathcal{L} = m_{\\text{action}}\\!\\cdot\\!\\mathcal{L}_{\\text{GRPO}} \\;+\\; m_{\\text{obs}}\\!\\cdot\\!w_{\\text{sup}}'}
              x={STAGE_W / 2}
              y={376}
              fontSize={26}
              color={colors.TEXT}
              display
            />
          </g>
        )}

        <Chip x={STAGE_W / 2} y={608} text="no new value network — selective log-prob + masking only" color={colors.POSITIVE} u={cheapChipU * fade} />
      </Camera>

      {/* closing panel */}
      {endU > 0.05 && (
        <rect
          x={STAGE_W / 2 - 420}
          y={280}
          width={840}
          height={160}
          rx={18}
          fill={colors.PANEL}
          opacity={0.92 * endU}
        />
      )}
      {endU > 0.3 && (
        <text
          x={STAGE_W / 2}
          y={368}
          textAnchor="middle"
          fill={colors.WARM}
          fontSize={22}
          fontWeight={600}
          opacity={endU}
        >
          the masking trick
        </text>
      )}
    </>
  );
}

export const vizScene = () => scene;
